chore(NODE-4250): remove unused platforms
mongodb-js/zstd pull request #3
Opened 2022-05-16 19:05 UTC by durran

Removes musl and android builds from the repository.

2022-05-16 20:20 UTC, nbbeeken requested changes

2022-05-17 14:03 UTC, durran commented on package.json
> +        "x86_64-unknown-freebsd"
Removed the CI tasks and updated the logic in the index.js

2022-05-17 15:41 UTC, nbbeeken requested changes

2022-05-17 16:37 UTC, nbbeeken approved these changes
LGTM once ci is ✅

2022-05-17 16:41 UTC, durran commented on package.json
> +        "x86_64-unknown-freebsd"
Updated.

2022-05-17 16:46 UTC, merged