chore(NODE-6574): remove `bindings` as a production dependency
mongodb-js/zstd pull request #42
Opened 2024-11-26 17:36 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run format:js && npm run format:rs` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-11-26 18:22 UTC, nbbeeken requested changes

2024-11-26 18:22 UTC, nbbeeken commented on lib/index.js
> +const zstd = require(resolve(__dirname, '../build/Release/zstd.node'));
```suggestion
const zstd = require('../build/Release/zstd.node');
```

No need to run the same resolution logic that require already has, plus the string literal is desirable to fix issues with bundlers (you can ignore/customize a hard-coded string easily)

2024-11-26 18:22 UTC, nbbeeken commented on lib/index.js
> +const zstd = require(resolve(__dirname, '../build/Release/zstd.node'));
What about attempting an import of the Debug version?

2024-11-26 18:54 UTC, nbbeeken commented on lib/index.js
> +const zstd = require(resolve(__dirname, '../build/Release/zstd.node'));
It's not something to be "set up" you just add a flag:

```sh
npx node-gyp rebuild --debug 
```

I don't think we'd ever ship Debug builds if that's what you mean by "set up". What are you imagining for that?

2024-11-26 20:59 UTC, nbbeeken approved these changes
LGTM

2024-11-27 09:42 UTC, addaleax approved these changes

2024-11-27 13:34 UTC, merged